# Generated by Django 5.2.1 on 2025-07-07 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_enrollment_options_alter_lesson_options'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='VIP名称')),
                ('vip_type', models.CharField(choices=[('year', '包年VIP'), ('forever', '永久VIP')], default='year', max_length=10, verbose_name='VIP类型')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('duration_days', models.IntegerField(blank=True, null=True, verbose_name='有效天数')),
            ],
            options={
                'verbose_name': 'VIP产品',
                'verbose_name_plural': 'VIP产品管理',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('course', '课程订单'), ('vip', 'VIP订单')], default='course', max_length=10, verbose_name='订单类型'),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_remark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='支付备注'),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_serial_no',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='支付流水号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_type',
            field=models.CharField(choices=[('wechat', '微信'), ('alipay', '支付宝'), ('other', '其他')], default='qrcode', max_length=20, verbose_name='支付方式'),
        ),
    ]
