# Generated by Django 5.2.1 on 2025-06-13 14:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_active_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最新活动时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='register_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间'),
        ),
    ]
