# Generated by Django 5.2.1 on 2025-07-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_vipproduct_order_order_type_order_pay_remark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vipproduct',
            name='name',
        ),
    ]
