# Generated by Django 5.2.1 on 2025-06-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_last_active_time_user_register_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='register_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册时间'),
        ),
    ]
