# Generated by Django 5.2.1 on 2025-07-07 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_vipproduct_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vip_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.vipproduct', verbose_name='VIP产品'),
        ),
    ]
