# Generated by Django 5.2.1 on 2025-07-07 14:47

import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='名称')),
                ('description', models.CharField(max_length=255, verbose_name='简介')),
                ('level', models.IntegerField(choices=[(3, '初级'), (2, '中级'), (1, '高级')], verbose_name='难度')),
                ('study_number', models.IntegerField(default=0, verbose_name='学习人数')),
                ('favorite_number', models.IntegerField(default=0, verbose_name='收藏数')),
                ('tell', mdeditor.fields.MDTextField(default='#### 课程须知\n如果有问题及时反馈  \n#### 你能学到什么\nDjango Ninja & React 前后端的使用\n', verbose_name='需要告知的内容')),
                ('image', models.ImageField(upload_to='courses/', verbose_name='图片')),
                ('is_feature', models.BooleanField(default=False, verbose_name='精选课程')),
                ('price', models.IntegerField(default=0, verbose_name='课程价格（元）')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '01-课程管理',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unpaid', '未支付'), ('paid', '已支付'), ('cancelled', '已取消')], default='unpaid', max_length=50)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '订购课程',
                'verbose_name_plural': '04-订购课程管理',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '收藏课程',
                'verbose_name_plural': '收藏课程管理',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('sort_number', models.IntegerField(default=1, verbose_name='序号')),
                ('free_preview', models.BooleanField(default=False)),
                ('video_source', models.CharField(choices=[('bili', 'Bilibili'), ('qiniu', 'Qiniu Cloud'), ('local', 'Local')], max_length=20)),
                ('video_url', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='courses/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '课时',
                'verbose_name_plural': '03-课时管理',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞管理',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签管理',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.comment', verbose_name='父评论')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论管理',
            },
        ),
    ]
