# Generated by Django 5.2.1 on 2025-07-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': '订购课程', 'verbose_name_plural': '03-订购课程管理'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': '课时', 'verbose_name_plural': '02-课时管理'},
        ),
    ]
