# Generated by Django 5.2.1 on 2025-06-13 15:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_price'),
        ('user', '0003_alter_user_register_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='join_time',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course', verbose_name='课程')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '操作记录',
                'verbose_name_plural': '用户操作记录',
            },
        ),
        migrations.DeleteModel(
            name='UserHub',
        ),
    ]
