# Generated by Django 5.2.1 on 2025-06-13 15:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_enrollment_join_time_enrollment_create_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': '订购课程', 'verbose_name_plural': '订购课程'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': '收藏课程', 'verbose_name_plural': '收藏课程'},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间'),
        ),
    ]
