# Generated by Django 5.2.1 on 2025-06-15 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_tag_remove_video_video_comment_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='briefly',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
    ]
