# Generated by Django 5.2.1 on 2025-06-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_rename_briefly_chapter_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='sort_number',
        ),
        migrations.AddField(
            model_name='course',
            name='is_feature',
            field=models.BooleanField(default=False, verbose_name='精选课程'),
        ),
    ]
