# Generated by Django 5.2.1 on 2025-06-29 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_alter_like_options_remove_course_like_number_and_more'),
        ('user', '0003_alter_user_register_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='favorite_number',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_set', to='course.course', verbose_name='课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏课程',
                'verbose_name_plural': '收藏课程管理',
            },
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
