# Generated by Django 5.2.1 on 2025-06-29 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_course_favorite_number_favorite_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='course.course', verbose_name='课程'),
        ),
    ]
